language: node_js
node_js:
- '14'
sudo: false
cache: yarn
branches:
  only:
  - master
before_script:
- npm install
script:
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- echo $TRAVIS_REPO_SLUG
- echo $GH_TOKEN
- echo ${TRAVIS_BUILD_NUMBER}
- echo ${BASH_SOURCE}
- echo ${TRAVIS_BUILD_DIR}
- cd $TRAVIS_BUILD_DIR
- chmod +x generateDocs.sh
- bash generateDocs.sh
