language: node_js
node_js:
- '14'
sudo: false
cache: yarn
branches:
  only:
  - master
before_script:
- npm install
script:
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- echo $TRAVIS_REPO_SLUG
- echo $GH_TOKEN
- echo ${TRAVIS_BUILD_NUMBER}
- echo ${BASH_SOURCE}
- echo ${TRAVIS_BUILD_DIR}
- cd $TRAVIS_BUILD_DIR
- chmod +x generateDocs.sh
- bash generateDocs.sh
env:
  global:
    secure: PY9FaiIUDW6KhD7ALVmkclVqECUHxiYPkjhZ+BTDy2m57BhJtqixgV/8Q5FTCdhTOFAMKRj4P+Clar98MBAXC08surorudyViiuCzC5tFpb2uEspQsxh/Ys/440svrNwoMCJRW5LQdfoP6n0qjV65lFq+eiOEHc5DxaFFt7PsFPUc29uGEqNlA8Xv6EuUH7kWqehsGxw9VAtbSQbDPANGJ438ZrnEbqX1xs936hIVTUPKHN7dP5tuc3/hcOQtNCjPu8bVesHYGrRWduYEzHfBlPft+1C8ocQoeN0WABqfn73vu3KVP7nH6RF08c2bUSLcIQTB3GB5o3hiH+wCy63Pi37z7dwnK0H4MpEPoUivbncMk5awtUnTpOXpO/XJO6X3EbHA0k/7moUcduNl8CShsywjA4ZhQqNQ68ANVRHCzIzjuR8oyA/b6CgrCQjOPqM4hrwb2jH9r70D57MYXicly9yQnn0HEnrKE7TtICErlS76CO/NMKwB/IiG79l9+4GMTeNX2+WK9U0rtZZOC4Ya6GLV5sauDB7q5yPm2aRrQwLQIKSjHl84mvb55jNteBaw4UZAG3IE884rjNIgJ2pY+LNy4FC/xuW3YI47a2tbuYFvmgWpUJPFtUM94Vre2m+Ff/TS4Qof4A4bFPp6bYRmF9e+sG4ZMQpxmSayYa2z6Q=
